spring:
  application:
    name: covid-web

  datasource:
    url: jdbc:mysql://bj-cynosdbmysql-grp-1h4t9vx8.sql.tencentcdb.com:26151/covid?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: reader
    password: 4a43F8a7418740E7903f9283f5f9cf33
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: "classpath:/mapper/**/*.xml"

server:
  port: 20000